# Generated by Django 5.2.10 on 2026-01-20 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('language', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('ru', 'Russian')], default='uk', max_length=2, verbose_name='Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='Parsed')),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last parsed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DailyInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('paragraph_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Paragraph ID')),
                ('original_text', models.TextField(verbose_name='Original text')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='HTML content')),
                ('translation_ukrainian', models.TextField(blank=True, null=True, verbose_name='Ukrainian translation')),
                ('translation_russian', models.TextField(blank=True, null=True, verbose_name='Russian translation')),
                ('translation_english', models.TextField(blank=True, null=True, verbose_name='English translation')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inspirations', to='core.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Daily inspiration',
                'verbose_name_plural': 'Daily inspirations',
                'ordering': ['-date', 'book'],
                'unique_together': {('book', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.TimeField(verbose_name='Notification time')),
                ('time_window_minutes', models.IntegerField(default=0, verbose_name='Time window (minutes, 0-9)')),
                ('language', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('ru', 'Russian')], default='uk', max_length=2, verbose_name='Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('selected_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='core.book', verbose_name='Selected book')),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.telegramuser', verbose_name='Telegram user')),
            ],
            options={
                'verbose_name': 'User settings',
                'verbose_name_plural': 'User settings',
            },
        ),
        migrations.CreateModel(
            name='SentInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('ru', 'Russian')], max_length=2, verbose_name='Language')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to_users', to='core.dailyinspiration', verbose_name='Inspiration')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inspirations', to='core.telegramuser', verbose_name='Telegram user')),
            ],
            options={
                'verbose_name': 'Sent inspiration',
                'verbose_name_plural': 'Sent inspirations',
                'ordering': ['-sent_at'],
                'unique_together': {('telegram_user', 'inspiration', 'language')},
            },
        ),
    ]
