# Generated by Django 5.2.10 on 2026-01-21 20:30

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usersettings_time_window_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Kyiv', verbose_name='Timezone'),
        ),
    ]
